from agarwals.settlement_advice_downloader.provider_ihx_downloader import ProviderIhx
from agarwals.settlement_advice_downloader.tips_vidalhealthtpa import TipsVidalHealthTpa
from agarwals.settlement_advice_downloader.tnnhis_mdindia import TnnhisMdIndia
from agarwals.settlement_advice_downloader.star_health_downloader import StarHealthDownloader
from agarwals.settlement_advice_downloader.vitrya_downloader import VitryaDownloader
